<script setup>
import backgroundAbstract3 from '@/assets/images/background-abstract-3.png?w=1024&format=webp&quality=82'
import backgroundAbstract3Srcset from '@/assets/images/background-abstract-3.png?w=480;800;1024&format=webp&quality=82&as=srcset'
import cuneiformWestbeach from '@/assets/images/CuneiformWestbeachThnxgiving.png?w=800&format=webp&quality=82'
import cuneiformWestbeachSrcset from '@/assets/images/CuneiformWestbeachThnxgiving.png?w=400;800&format=webp&quality=82&as=srcset'
import fieldAmp from '@/assets/images/alex-field-amp-cropped-1.png?w=800&format=webp&quality=82'
import fieldAmpSrcset from '@/assets/images/alex-field-amp-cropped-1.png?w=400;800&format=webp&quality=82&as=srcset'
import garagePhoto from '@/assets/images/garage-photo-cropped.png?w=1400&format=webp&quality=82'
import garagePhotoSrcset from '@/assets/images/garage-photo-cropped.png?w=480;800;1400&format=webp&quality=82&as=srcset'
</script>

<template>
  <main class="atacamamedium bg-stock-blush pt-14 lg:pt-20 text-black">

    <div class="section-panel">
      <img :src="backgroundAbstract3" :srcset="backgroundAbstract3Srcset" sizes="(min-width: 1024px) 1400px, 100vw" alt="" width="1024" height="248" class="aspect-[3/2] md:aspect-[21/9] md:max-h-[40vh] lg:aspect-[1024/248] lg:max-h-none w-full object-cover object-[75%_center]"/>
      <h1 class="hero-headline">All tech and no music<br>makes Alex a dull boy</h1>
    </div>
    <div class="px-2 sm:px-4 md:px-0 lg:px-0 body-column mt-6 lg:pl-48">
      <p class="alaska text-3xl">
        <em>Sound is not a backdrop.</em>
      </p>
    </div>
    <div class="flex px-2 sm:px-4 md:px-8">
      <div class="hidden lg:inline w-1/4 lg:pr-8">
      </div>
      <div class="w-full body-column lg:w-3/4">
        <div class="prose-col mt-6 mb-8">
          <p class="body-copy">
            Every sound is an event generated by vibrating bodies, shaped by the spaces between them, and completed inside the listener.
          </p>
        </div>
        <div class="prose-col mb-8">
          <p class="body-copy">
            My mind lives at that intersection: the drum as acoustic instrument, the microphone as witness, and the space around them as the site where music, <em>and culture</em>, actually happens.
          </p>
          <p class="body-copy">
            I’ve never been satisfied as a cog in a soulless machine.
            I haven’t followed a straight professional path.
            Most things I’ve done that mattered were born from personal projects, from freelance work, and from figuring things out on the fly.
            Engaging and cultivating something <em>REAL</em> takes time.<br><br>
            <em class="alaska text-3xl">It takes…<span class="inline-block w-4 lg:w-8"></span>
              <span class="inline lg:hidden"><br></span>
              So.<span class="inline-block w-2 lg:w-8"></span>
              Much.<span class="inline-block w-2 lg:w-8"></span>
              Time.</em>
          </p>
        </div>
        <div class="lg:pl-[40rem] mb-8 lg:mb-16">
          <div class="flex align-baseline lg:max-w-[18rem] pt-6 lg:pt-8 pb-4 relative z-0">
            <p><span class="alaska tracking-tight mr-2"><em>kaizen (Japanese):</em></span>
              <em class="alaska">The practice of continually seeking improvement.</em>
            </p>
          </div>
        </div>
        <div class="prose-col lg:mb-8">
          <p class="body-copy">
            I didn’t know the word “ideology” when I first felt it, but I knew it was everywhere.
            Trying to make sense of the world involves plodding through a web of conflicting beliefs.
            Each one louder than the last.<br><br>
            <em>That’s what makes life <s>exhausting</s> fascinating.<br>
              That’s what makes life exhausting <s>fascinating</s>.</em>
          </p>
          <p class="body-copy">
            <em class="alaska text-xl">Maybe none of it is supposed to make sense…</em>
          </p>
          <p class="body-copy">
            I was born in upstate New York, spent my childhood in the mountains of western Massachusetts,
            then landed in rural Arizona at thirteen. The desert, border towns, a different world entirely.
          </p>
        </div>
        <div class="pb-8">
          <ul class="alaska body-copy">
            <li>Since then:</li>
            <li class="text-3xl lg:pl-[4rem]">San Francisco</li>
            <li class="text-3xl pl-3 lg:pl-[12rem]">Tucson</li>
            <li class="text-3xl pl-6 lg:pl-[24rem]">L.A.</li>
            <li class="text-3xl pl-9 lg:pl-[36rem]">Vegas</li>
            <li class="text-3xl pl-12 lg:pl-[48rem]">Eugene</li>
          </ul>
        </div>
        <div class="prose-col lg:mb-8">
          <p class="body-copy lg:mb-16">
            In these different situations, I’ve known an unclassifiable blend of people from drastically different walks of life.
            Still, I haven’t found a believable ready-made worldview and I’m sure I won’t. That feeling only gets stronger. I’m not wired for doctrine.
            Maybe that’s why I keep on going, discovering meaning the only way I know how:  through logic, through art, through rhythm.
          </p>
          <p class="body-copy mb-16">
            More about my
            <a href="/music" class="highlight-link">
              music background
            </a>
            <br>and
            <a href="/design" class="highlight-link">
              design background</a>.
          </p>
        </div>
      </div>
    </div>

    <div class="section-panel">
      <div class="w-full flex flex-col md:flex-row pb-0 md:pb-2">
        <div class="mb-4 md:mb-0 md:w-[50%] md:pr-2">
          <img :src="fieldAmp" :srcset="fieldAmpSrcset" sizes="(min-width: 768px) 50vw, 100vw" alt="Sitting in a field adjusting an amplifier" width="1024" height="761" loading="lazy" class="w-full"/>
          <span class="photo-caption">
            2020: Dabbling with audio equipment in a field near Eugene, OR
          </span>
        </div>
        <div class="mb-4 md:mb-0 md:w-[50%] md:pl-2">
          <img :src="cuneiformWestbeach" :srcset="cuneiformWestbeachSrcset" sizes="(min-width: 768px) 50vw, 100vw" alt="Listening back to a drum recording at Westbeach Studios, Hollywood, CA" width="1024" height="761" loading="lazy" class="w-full"/>
          <span class="photo-caption">
           2007: Listening back to a drum recording at Westbeach Studios, Hollywood, CA
          </span>
        </div>
      </div>
      <img :src="garagePhoto" :srcset="garagePhotoSrcset" sizes="(min-width: 1024px) 1400px, 100vw" alt="Hanging out with recording equipment in a home garage studio, Eugene, OR" width="3000" height="1346" loading="lazy" class="w-full h-auto border border-gray-400"/>
      <span class="photo-caption mb-2">
        2024: Hanging out with some equipment in my garage, Eugene, OR
      </span>
    </div>
  </main>
</template>
