<script setup>
import backgroundAbstract3 from '@/assets/images/background-abstract-3.png'
import cuneiformWestbeach from '@/assets/images/CuneiformWestbeachThnxgiving.png'
import fieldAmp from '@/assets/images/alex-field-amp-cropped-1.png'
import garagePhoto from '@/assets/images/garage-photo-cropped.png'
</script>

<template>
  <main class="atacamamedium bg-[#F6D9CE] text-[#444244] pt-20 text-black">

    <div class="section-panel">
      <img :src="backgroundAbstract3" alt="" width="1024" height="248" class="w-full"/>
      <h1 class="swissposters font-light text-[10rem]/[1] pb-8 w-full">All tech and no music<br>makes Alex a dull boy</h1>
    </div>
    <div class="mt-6 mb-8 pl-48">
      <p class="alaska mb-8 text-3xl">
        <em>Sound is not a backdrop.</em>
      </p>
    </div>
    <div class="flex px-2 sm:px-4 md:px-8">
      <div class="hidden lg:inline w-1/4 lg:pr-8">
      </div>
      <div class="w-full lg:w-3/4">
        <div class="prose-col mt-6 mb-8">
          <p class="body-copy">
            Every sound is an event generated by vibrating bodies, shaped by the spaces between them, and completed inside the listener.
          </p>
        </div>
        <div class="prose-col mb-8">
          <p class="body-copy">
            My mind lives at that intersection: the drum as acoustic instrument, the microphone as witness, and the space around them as the site where music, <em>and culture</em>, actually happens.
          </p>
          <p class="body-copy">
            I’ve never been satisfied as a cog in a soulless machine.
            I haven’t followed a straight professional path.
            Most things I've done that mattered were born from personal projects, from freelance work, and from figuring things out on the fly.
            Engaging and cultivating something <em>REAL</em> takes time.<br><br>
            <em class="alaska text-3xl">It takes...&nbsp;&nbsp;&nbsp;&nbsp;
              <span class="inline lg:hidden"><br></span>
              So.&nbsp;&nbsp;&nbsp;&nbsp;
              Much.&nbsp;&nbsp;&nbsp;&nbsp;
              Time.</em>
          </p>
        </div>
        <div class="md:pl-[40rem] mb-16">
          <div class="flex align-baseline md:max-w-[18rem] pt-8 pb-4 relative z-0">
            <p><span class="alaska tracking-tight mr-2"><em>kaizen (Japanese):</em></span>
              <em class="atacama font-thin">The practice of continually seeking improvement.</em>
            </p>
          </div>
        </div>
        <div class="prose-col md:mb-8">
          <p class="body-copy">
            I didn’t know the word “ideology” when I first felt it, but I knew it was everywhere.
            Trying to make sense of the world involves plodding through a web of conflicting beliefs.
            Each one louder than the last.<br><br>
            <em>That’s what makes life <s>exhausting</s> fascinating.<br>
              That’s what makes life exhausting <s>fascinating</s>.</em>
          </p>
          <p class="mb-8">
            <em class="alaska text-xl">Maybe none of it is supposed to make sense...</em>
          </p>
          <p class="body-copy leading-10">
            I was born in upstate New York, spent my childhood in the mountains of western Massachusetts,
            then landed in rural Arizona at thirteen. The desert, border towns, a different world entirely.
          </p>
        </div>
        <div class="pb-8">
          <ul class="alaska body-copy">
            <li>Since then:</li>
            <li class="text-3xl pl-[4rem]">San Francisco</li>
            <li class="text-3xl pl-[12rem]">Tucson</li>
            <li class="text-3xl pl-[24rem]">L.A.</li>
            <li class="text-3xl pl-[36rem]">Vegas</li>
            <li class="text-3xl pl-[48rem]">Eugene</li>
          </ul>
        </div>
        <div class="prose-col md:mb-8">
          <p class="body-copy mb-16">
            In these different situations, I’ve known an unclassifiable blend of people from drastically different walks of life.
            Still, I haven't found a believable ready-made worldview and I'm sure I won't. That feeling only gets stronger. I’m not wired for doctrine.
            Maybe that’s why I keep on going, discovering meaning the only way I know how:  through logic, through art, through rhythm.
          </p>
          <p class="body-copy mb-16">
            More about my
            <a href="/music" class="highlight-link">
              music background
            </a>
            <br>and
            <a href="/design" class="highlight-link">
              design background</a>.
          </p>
        </div>
      </div>
    </div>

    <div class="section-panel">
      <div class="w-full flex pb-2">
        <div class="md:w-[50%] pr-2">
          <img :src="fieldAmp" alt="Sitting in a field adjusting an amplifier" width="1024" height="761" loading="lazy"/>
          <span class="photo-caption">
            2020: Dabbling with audio equipment in a field near Eugene, OR
          </span>
        </div>
        <div class="md:w-[50%] pl-2">
          <img :src="cuneiformWestbeach" alt="Listening back to a drum recording at Westbeach Studios, Hollywood, CA" width="1024" height="761" loading="lazy"/>
          <span class="photo-caption">
           2007: Listening back to a drum recording at Westbeach Studios, Hollywood, CA
          </span>
        </div>
      </div>
      <img :src="garagePhoto" alt="Hanging out with recording equipment in a home garage studio, Eugene, OR" width="3000" height="1346" loading="lazy" class="w-full h-auto border border-gray-400"/>
      <span class="photo-caption mb-2">
        2024: Hanging out with some equipment in my garage, Eugene, OR
      </span>
    </div>
  </main>
</template>
