<script setup>
import backgroundAbstract3 from '@/assets/images/background-abstract-3.png'
import cuneiformWestbeach from '@/assets/images/CuneiformWestbeachThnxgiving.png'
import fieldAmp from '@/assets/images/alex-field-amp-cropped-1.png'
import garagePhoto from '@/assets/images/garage-photo-cropped.png'
</script>

<template>
  <div class="atacamamedium bg-[#F6D9CE] text-[#444244] pt-20 text-black">

    <div class="md:mx-8 relative">
      <!--<img :src="garagePhoto" alt="Garage music" width="auto" class="w-full h-auto"/> -->
      <div class="absolute w-full h-full top-0 left-0 flex">
        <div class="hidden lg:inline w-1/4 lg:pr-8">
        </div>
        <div class="w-full lg:w-3/4 flex flex-col pb-8">
          <!--<h2 class="neogeo text-5xl/[1] text-white md:max-w-[15ch] mt-auto">All tech and no music <span class="hidden lg:inline"><br></span>makes Alex a dull boy.</h2>-->
        </div>
      </div>
      <img :src="backgroundAbstract3" alt="Garage music" width="full" class="w-full"/>
      <h2 class="swissposters font-light text-[10rem]/[1] pb-8 w-full">All tech and no music<br>makes Alex a dull boy</h2>
    </div>
    <div class="flex px-2 sm:px-4 md:px-8 ">
      <div class="hidden lg:inline w-1/4 lg:pr-8">
      </div>
      <div class="w-full lg:w-3/4">
        <div class="md:max-w-[18ch] mt-6 mb-8">
          <p class="alaska mb-8 text-3xl">
            <em>Sound is not a backdrop.</em>
          </p>
          <p class="mb-8 text-xl leading-8">
            Every sound is an event generated by vibrating bodies, shaped by the spaces between them, and completed inside the listener.
          </p>
        </div>
        <div class="md:max-w-[15ch] mb-8">
          <p class="mb-8 text-xl leading-8">
            My mind lives at that intersection: the drum as acoustic instrument, the microphone as witness, and the space around them as the site where music, <em>and culture</em>, actually happens.
          </p>
          <p class="mb-8 text-xl leading-8">
            I’ve never been satisfied as a cog in a soulless machine.
            I haven’t followed a straight professional path.
            Most things I've done that mattered were born from personal projects, from freelance work, and from figuring things out on the fly.
            Engaging and cultivating something <em>REAL</em> takes time.<br><br>
            <em class="alaska text-3xl">It takes...&nbsp;&nbsp;&nbsp;&nbsp;
              <span class="inline lg:hidden"><br></span>
              So.&nbsp;&nbsp;&nbsp;&nbsp;
              Much.&nbsp;&nbsp;&nbsp;&nbsp;
              Time.</em>
          </p>
          <p>

          </p>
        </div>

        <div class="md:max-w-[15ch] md:mb-8">
          <p class="mb-8 text-xl leading-8">
            I didn’t know the word “ideology” when I first felt it, but I knew it was everywhere.
            Trying to make sense of the world involves plodding through a web of conflicting beliefs.
            Each one louder than the last.<br><br>
            <em>That’s what makes life <strike>exhausting</strike> fascinating.<br>
              That’s what makes life exhausting <strike>fascinating</strike>.</em>
          </p>
          <p class="mb-8">
            <em class="alaska text-3xl">Maybe none of it is supposed to make sense...</em>
          </p>
          <p class="leading-10 mb-8 text-xl leading-10">
            I was born in upstate
            <span class="alaska text-3xl">New York,</span>
            spent my childhood in the mountains of western
            <span class="alaska text-3xl">Massachusetts,</span>
            then landed in rural
            <span class="alaska text-3xl">Arizona</span>
            at thirteen. The desert, border towns, a different world entirely.
          </p>

          <ul class="alaska mb-8 text-xl leading-8">
            <li>Since then:</li>
            <li class="text-3xl">San Francisco</li>
            <li class="text-3xl">Tucson</li>
            <li class="text-3xl">L.A.</li>
            <li class="text-3xl">Vegas</li>
            <li class="text-3xl">Eugene</li>
          </ul>
          <p class="mb-8 text-xl leading-8">
            In these different situations, I’ve known an unclassifiable blend of people from drastically different walks of life.
            Still, I haven't found a believable ready-made worldview and I'm sure I won't. That feeling only gets stronger. I’m not wired for doctrine.
            Maybe that’s why I keep on living. Discovering meaning the only way I know how:  through logic, through art, through rhythm.
          </p>
          <p class="alaska text-3xl mb-8 leading-8">
            More about <a href="/projects/music" class="text-red-500" target="_blank">bands</a>
          </p>
          <p class="alaska text-3xl leading-8">
            More about <a href="/projects/design" class="text-red-500" target="_blank">design</a>
          </p>
          <div class="flex align-baseline pt-8 pb-4 relative z-0">
            <p><span class="alaska tracking-tight mr-2"><em>kaizen (Japanese):</em></span>
              <em class="atacama font-thin">The practice of continually seeking improvement.</em>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="md:mx-8 relative">
      <div class="w-full flex pb-4">
        <div class="md:w-[50%] pr-2">
          <img :src="fieldAmp" alt="Sitting in a field adjusting an amplifier" width="full"/>
        </div>
        <div class="md:w-[50%] pl-2">
          <img :src="cuneiformWestbeach" alt="Garage music" width="full"/>
        </div>
      </div>
      <img :src="garagePhoto" alt="Garage music" width="auto" class="w-full h-auto mb-4"/>
      <span class="font-thin italic inline-block mb-4">2020: Dabbling with audio equipment in a field near Eugene, Oregon.</span>
    </div>
  </div>
</template>
